### ISSUE TITLE
Which library should we be using for validation ?

### ISSUE THREAD

**Issue by inverted-capital** [mikeal/ipld-schema-validation#1]
Hi - there are two libraries.  This one which has been published at https://www.npmjs.com/package/@ipld/schema-validation and also https://www.npmjs.com/package/ipld-schema-validator - why are there two, with common people between each project ?

**Comment by inverted-capital** [comment]
I'm terribly sorry - I mispelled the package name as `ipld-schema-validation`

**Comment by rvagg** [comment]
At this stage both libraries are out of date, this one more than the other. I'm going to try and find time to sort this all out and update the JS schema parser and validation tools soon; I'm not sure what I'll do with this package but it may be deprecated and replaced with an `@ipld/schema-validator` that builds on from the one currently published as `ipld-schema-validator`.
